services:
  db:
    image: mariadb:11
    container_name: izac-db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: StrongAdminPassword123
      MARIADB_DATABASE: izac_db
      MARIADB_USER: izac_api
      MARIADB_PASSWORD: StrongPassword123
    ports:
      - '3307:3306'
    volumes:
      - izac_db_data:/var/lib/mysql

volumes:
  izac_db_data:
